ansible/event-driven-ansible

README.md, benthomasson/eda/plugins/event_source/kafka.py, benthomasson/eda/rules/kafka-test-rules.yml
=> Add kafka source plugin

benthomasson/eda/plugins/event_source/alertmanager.py, benthomasson/eda/plugins/event_source/webhook.py
Convert to asyncio and aiohttp
https://issues.redhat.com/browse/AAP-4385
https://issues.redhat.com/browse/AAP-4386
=> Replace flask with async aiohttp server for webhook and alertmanager

benthomasson/eda/galaxy.yml, benthomasson/eda/plugins/event_filter/dashes_to_underscores.py, benthomasson/eda/plugins/event_filter/json_filter.py, benthomasson/eda/plugins/event_filter/noop.py, benthomasson/eda/plugins/event_source/azure_service_bus.py, benthomasson/eda/plugins/event_source/file.py, benthomasson/eda/plugins/event_source/url_check.py, benthomasson/eda/plugins/event_source/watchdog.py, benthomasson/eda/plugins/modules/upcase.py
This PR fix the errors reported when running `ansible-test sanity` under the ansible collection location.
https://issues.redhat.com/browse/AAP-5047
=> Fix errors from 'ansible-test sanity' checking

.github/workflows/tests.yml, .gitignore
Depends on https://github.com/benthomasson/benthomasson-eda/pull/7
=> add github workflow to run sanity tests

benthomasson/eda/plugins/event_source/webhook.py, benthomasson/eda/tests/unit/event_source/test_webhook.py, benthomasson/eda/tests/unit/requirements.txt
Passed test command:
```
ansible-test units --docker default
```
=> Add ansible-test unit test for webhook plugin

.github/workflows/tests.yml
https://issues.redhat.com/browse/AAP-5426
=> Add ansible-test unit testing to workflow

plugins/event_source/file_watch.py
Requires https://github.com/ansible/ansible-rulebook/pull/178
=> Updates file watching plugin

README.md
This PR:
- fixes 'no-smart-quotes' error, see https://github.com/ansible/event-driven-ansible/actions/runs/3276986849/jobs/5393792379#step:6:79
- performs some basic markdown linting
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>
=> 'no-smart-quotes' fix and linting

test_requirements.txt, tests/integration/conftest.py, tests/integration/event_source_webhook/test_webhook_rules.yml, tests/integration/event_source_webhook/test_webhook_source.py, tests/integration/utils.py
#23 fixes the failing integration test.
=> Adding integration test for webhook plugin

tests/integration/conftest.py, tests/integration/event_source_url_check/test_url_check_rules.yml, tests/integration/event_source_url_check/test_url_check_source.py, tests/integration/event_source_url_check/webserver_files/index.html
=> Add url_check plugin integration tests

plugins/event_source/kafka.py
ref: https://github.com/ansible/event-driven-ansible/issues/61
Signed-off-by: morvencao <lcao@redhat.com>
=> add ssl support for kafka source.

.github/workflows/integration-tests.yml, requirements.txt, test_requirements.txt, tests/integration/conftest.py, tests/integration/event_source_url_check/test_url_check_source.py, tests/integration/event_source_webhook/test_webhook_source.py, tests/integration/utils.py
- Install jdk v17
- Use pypi release of ansible-rulebook
- Refactor webhook integration tests, requirements and remove unused code
- Increase verbose of pytest
Closes: https://issues.redhat.com/browse/AAP-8891
=> Fix integration tests: refactor reqs and add jdk v11

tests/integration/event_source_webhook/test_webhook_source.py
Fixes flakyness of webhook tests replacing the sleep with a wait for func.
=> Remove sleep in webhook integration tests

plugins/event_source/aws_sqs_queue.py, requirements.txt, tests/conftest.py, tests/unit/event_source/test_aws_sqs_queue.py, tests/unit/requirements.txt
Refactor the arguments
Add unit test
The plugin name and connection argument are aligned with other aws plugins.
=> [AAP-9555] Rename sqs.py to aws_sqs_queue.py

plugins/event_source/aws_cloudtrail.py, plugins/event_source/aws_sqs_queue.py, plugins/utils/aws_utils.py, tests/unit/event_source/test_aws_cloudtrail.py, tests/unit/event_source/test_aws_sqs_queue.py
Add unit test
Resolves AAP-9555: [COLLECTION] Unify the param list for aws source plugins
Follow-up #79
=> [AAP-9555] Refactor parameters for aws_cloudtrail

README.md
=> Fix doc about how to install dependencies

requirements.txt
=> Remove dupe aiobotocore package from requirements

extensions/eda/plugins/event_sources/generic.py
To be used for mocking events in EDA e2e tests.
Closes [AAP-11535](https://issues.redhat.com/browse/AAP-11535).
=> Add generic source plugin for testing purposes

extensions/eda/rulebooks/demo_controller_rulebook.yml
When a new controller is installed it has a default job template called
* Demo Job Template
The demo_controller_rulebook.yml tries executing that job template
=> Use Demo Job Template in a rulebook

galaxy.yml
Add usual venv's in the exclude list
=> Extend excluded files for the build

extensions/eda/plugins/event_source/url_check.py
This allows to use it with self-signed certificates.
=> Add verify_ssl option to url_check plugin

galaxy.yml
We need these to upload the collection to hub
=> Add galaxy tags and bump version

galaxy.yml
Hopefully the title is self-explanatory 😄
=> Bump version to 1.4.2

extensions/eda/plugins/event_source/aws_sqs_queue.py
Updated example to be the actual module name
=> Update aws_sqs_queue.py example

extensions/eda/plugins/event_source/file_watch.py
=> Fix typehint error in filewatch plugin

extensions/eda/plugins/event_source/aws_sqs_queue.py, extensions/eda/plugins/event_source/url_check.py
Ref https://github.com/ansible/event-driven-ansible/actions/runs/5540583359/jobs/10112863355#step:4:15 and https://github.com/ansible/event-driven-ansible/pull/149
=> tox test: ruff .278 requires capital letters

plugins/modules/activation.py, tests/integration/targets/rulebook_activations/tasks/main.yml
Added awx token id to rulebook activation module from version 1.0.7
=> update rulebook activation with awx token id

extensions/eda/plugins/event_source/alertmanager.py, tests/integration/event_source_webhook/test_webhook_source.py, tests/unit/event_source/test_alertmanager.py, tests/unit/event_source/test_webhook.py
See:  https://issues.redhat.com/browse/AAP-23958
=> [AAP-23958] -  Investigate errors in unit tests in eda collection

.github/workflows/tox.yml
=> Enable testing with python 3.11 and 3.12

.github/workflows/tox.yml, tox.ini
This allows us to provide better coverage while keeping the number of jobs under control.
Related: #219
Fixing: AAP-28986
=> Chain tests specific to a python-platform into single jobs

.github/workflows/tox.yml
Depends-On: https://github.com/coactions/dynamic-matrix/releases/tag/v3.0.1
Partial-Fix: https://github.com/ansible/event-driven-ansible/issues/219
AAP-28987
=> Enable testing with an arm64 linux runner

.github/workflows/tox.yml, .gitignore, codecov.yml, pyproject.toml, test_requirements.txt, tox.ini
Partial-Fix: https://github.com/ansible/event-driven-ansible/issues/219
AAP-28987
=> Enable coverage collecting and reporting

extensions/eda/plugins/event_source/alertmanager.py, extensions/eda/plugins/event_source/aws_cloudtrail.py, extensions/eda/plugins/event_source/aws_sqs_queue.py, extensions/eda/plugins/event_source/azure_service_bus.py, extensions/eda/plugins/event_source/file_watch.py, extensions/eda/plugins/event_source/generic.py, extensions/eda/plugins/event_source/journald.py, extensions/eda/plugins/event_source/kafka.py, extensions/eda/plugins/event_source/pg_listener.py, extensions/eda/plugins/event_source/range.py, extensions/eda/plugins/event_source/tick.py, extensions/eda/plugins/event_source/url_check.py, extensions/eda/plugins/event_source/webhook.py, pyproject.toml
=> Address arg-type, return and return-value type errors

extensions/eda/plugins/event_source/aws_sqs_queue.py, extensions/eda/plugins/event_source/journald.py, pyproject.toml, tests/integration/event_source_webhook/test_webhook_source.py
=> Address index, union-attr and misc typing errors

plugins/modules/decision_environment.py, plugins/modules/decision_environment_info.py, tests/integration/targets/decision_environment/tasks/create.yml, tests/integration/targets/decision_environment/tasks/delete.yml, tests/integration/targets/decision_environment/tasks/main.yml, tests/integration/targets/decision_environment/tasks/update.yml, tests/integration/targets/decision_environment_info/tasks/list.yml, tests/integration/targets/decision_environment_info/tasks/main.yml
* new module for managing project
* new module for listing project info
* tests
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
=> Add decision environment module

.config/dictionary.txt, meta/runtime.yml, plugins/module_utils/controller.py, plugins/modules/credential.py, plugins/modules/credential_info.py, tests/integration/targets/credential/tasks/main.yml
Add credential and credential_info modules
=> Add credential and credential_info modules

.pre-commit-config.yaml, extensions/eda/plugins/event_source/aws_cloudtrail.py, extensions/eda/plugins/event_source/azure_service_bus.py, extensions/eda/plugins/event_source/file.py, extensions/eda/plugins/event_source/file_watch.py, extensions/eda/plugins/event_source/journald.py, plugins/modules/project_info.py, pyproject.toml
=> Address more typing errors

extensions/eda/plugins/event_source/pg_listener.py, tests/unit/event_source/test_pg_listener.py
Log and raise the OperationalError/Decoding errors
https://issues.redhat.com/browse/AAP-30107
=> fix: raise OperationalError and Decoding Errors

README.md
Fix CHANGELOG reference path into README
=> Fix CHANGELOG reference path into README

.github/dependabot.yml
=> Tell dependabot to not update bleach

.config/manifest.txt, examples/eda-setup.yml
Provide an example about how the collection can be used in a playbook for a basic setup of EDA. 
Jira: issues.redhat.com/browse/AAP-30389
=> chore: add example playbook for basic setup

.config/manifest.txt, examples/eda-setup.yml, galaxy.yml, meta/runtime.yml, plugins/modules/credential_info.py, plugins/modules/credential_type.py, plugins/modules/credential_type_info.py, plugins/modules/event_stream_info.py, plugins/modules/rulebook_activation.py, plugins/modules/rulebook_activation_info.py, plugins/modules/rulebook_info.py, plugins/modules/user.py
- Fix some warning issues raised by ansible-lint.
- Remove tests/config.yml file so the certified collection pipeline can honor the supported python versions.
=> chore: fix lint issues and include tests config in collection tarball

plugins/modules/controller_token.py, plugins/modules/credential.py, plugins/modules/credential_info.py, plugins/modules/credential_type.py, plugins/modules/credential_type_info.py, plugins/modules/decision_environment.py, plugins/modules/decision_environment_info.py, plugins/modules/project.py, plugins/modules/project_info.py, plugins/modules/rulebook_activation.py, plugins/modules/rulebook_activation_info.py, plugins/modules/user.py
=> Improve documentation

tests/integration/event_source_kafka/docker-compose.yml
replace docker.io registry with mirror.gcr.io registry
=> chore: remove docker

.config/dictionary.txt, extensions/eda/plugins/event_filter/dashes_to_underscores.py, extensions/eda/plugins/event_filter/insert_hosts_to_meta.py, extensions/eda/plugins/event_filter/json_filter.py, extensions/eda/plugins/event_filter/noop.py, extensions/eda/plugins/event_filter/normalize_keys.py
This PR adds new documentation format for event filters plugins as part of our efforts in supporting EDA plugin documentation. 
JIRA: [AAP-38755](https://issues.redhat.com/browse/AAP-38755)
=> feat: [AAP-38755] add documentation for event filter plugins

CONTRIBUTING.md, README.md
Fixes https://github.com/ansible/event-driven-ansible/issues/411
=> docs: fix outdated ansible-rulebook docs link

plugins/modules/controller_token.py, plugins/modules/event_stream.py, plugins/modules/project.py
This PR does a bit of cleaning up by removing unnecessary `type` keyword in variables.
Introduces no functional change in the code.
=> chore: remove unnecessary 'type' keyword from variables

README.md, galaxy.yml
- change links in README to be full url link
- update homepage for the collection
=> fix: update links in README

.github/workflows/tox.yml
- remove duplicate `py312-unit` in tox.yml
- change mismatched py312 with py311
=> fix: remove duplicates and update mismatched python versions in tox.yml

plugins/module_utils/client.py, tests/unit/event_source/test_webhook.py, tests/unit/plugins/module_utils/test_client.py
this is my attempt to fix the hostname sanitization with what I believe were the requested changes in #363
=> sanitize hostname URL with startswith validation
