ansible/event-driven-ansible

benthomasson/eda/plugins/event_source/range_input_schema.json
benthomasson/eda/plugins/event_source/range_output_schema.json

The json schemas are in separate files one for input and one
for output. The input could most probably be used by the UI
the output is what would be sent to the drools engine as object
definition

Added json schema for range plugin

---

benthomasson/eda/plugins/event_source/url_check.py

Typing is not enforced for "delay" and if, for example, you set it to "5" instead of 5 then ansible-events will not loop; it runs once and exits because asyncio.sleep will not accept a string. This is a problem if you use jinja templating in your rulebook since it will always parse as a string. 
https://issues.redhat.com/browse/AAP-5497

Ensure arg 'delay' is always an integer

---

README.md

This is for some reason necessary again even though was #32 merged but `no-smart-quotes` is triggered yet again, see https://github.com/ansible/event-driven-ansible/actions/runs/3289246797/jobs/5420548015#step:5:79
This PR:
- replaces Unicode quotes again
- removes end-of-line whitespaces
related: #30 
Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

replace Unicode quotes and remove end-of-line whitespaces

---

README.md

This PR updates the example to reflect the syntax change introduced by https://github.com/ansible/event-driven-ansible/commit/e5c78e6ad4c144ec3526bee4a9c8968c2e371fcb.

Update README example to use rulebook

---

demos/dynatrace-demo/fake_app.py
demos/dynatrace-demo/instructions.md
demos/dynatrace-demo/inventory.yml
demos/dynatrace-demo/playbook.yml
demos/dynatrace-demo/rulebook.yml
galaxy.yml
plugins/event_source/alertmanager.py

We can use the existing (enhanced by #42) alertmanager and json_filter to integrate EDA with Dynatrace. Here is the an example on how to monitor the availability of a process and restart it if it crashes.
After some discussion with Ben we felt we should place our demos in this repository. I created demos folder which is excluded from the ansible-galaxy collection installation

Dynatrace demo

---

roles/install_ansible_rulebook/tasks/install_fedora.yml
roles/install_ansible_rulebook/tasks/install_macosx.yml

Fixes AAP-6385
Ansible and ansible-runner are indirect dependencies and must be managed in the system regardless of ansible-rulebook. The playbook started to install them by convenience. But since can be installed in a system scope, the playbook can fail trying to update them, so to avoid errors, better to move as "present" if those packages were previously installed by the user.

[AAP-6385] fix ansible dependencies for install-rulebook role

---

roles/install_ansible_rulebook/tasks/main.yml
roles/install_ansible_rulebook/vars/RedHat-8.yml

The python3* packages in RHEL8 differ to other OS' in that they point to an older version of Python (3.6). We need to override the package_list var for RHEL8 to ensure that Python3.9 is installed, not 3.6.

Override RHEL8 package_list var for CLI installer

---

.github/workflows/installer-tests.yml
tests/integration/targets/test_install_ansible_rulebook/files/hello.yml
tests/integration/targets/test_install_ansible_rulebook/files/inventory
tests/integration/targets/test_install_ansible_rulebook/tasks/main.yml

Adding a Github workflow to run ansible-test against the `install_ansible_rulebook` role whenever changes are made. This workflow will cover tests for Debian, RHEL-like and MacOS systems.
Also adding a new test role under `roles/test` which is required by ansible-test.
This PR depends on changes made in #51.

Add Github workflow tests for ansible-rulebook installer

---

.github/workflows/installer-tests.yml
roles/install_ansible_rulebook/README.md
roles/install_ansible_rulebook/defaults/main.yml
roles/install_ansible_rulebook/tasks/main.yml
tests/integration/targets/test_install_ansible_rulebook/tasks/main.yml

We want to allow for the installation of the EDA collection from the source repo. This will allow us to work around issues such as hitting Galaxy API limits in our workflows.

Allow installation of collection from source

---

roles/install_ansible_rulebook/tasks/main.yml

Closes [AAP-7759](https://issues.redhat.com/browse/AAP-7759). Removing env var from installer playbook since we no longer need to force compilation of JPY from source.

Remove PIP_NO_BINARY env var

---

plugins/event_source/webhook.py

Allow an empty endpoint for webhook plugin
Fixes https://github.com/ansible/event-driven-ansible/issues/57
Fixes https://github.com/ansible/ansible-rulebook/issues/236

Allow empty endpoint in webhook plugin

---

plugins/event_source/aws_cloudtrail.py
requirements.txt
tests/integration/event_source_aws_cloudtrail/test_awscloudtrail_rules.yml

This PR adds support to AWS Cloudtrail as an event source and includes an example rulebook.

Add AWS Cloudtrail event source plugin

---

plugins/event_filter/insert_hosts_to_meta.py
tests/unit/event_filter/test_insert_hosts_to_meta.py

This filter can be used together with any source plugins if the event data contains hosts that should be known by ansible-rulebook to run an ansible action.

Add a filter that finds hosts and inserts them to meta

---

tests/unit/event_source/test_alertmanager.py

Quick fix intermittent alertmanager unit test failures.
Issue to further troubleshoot why the port is not always releasing in time: https://issues.redhat.com/browse/AAP-9914

Fix intermittent alertmanager unit test failures

---

plugins/event_source/journald.py

This PR:
- converts all journald fields to strings so we don't have to worry about UUID and such
- ensures all journald fields are added to the dict
- closes #85

convert journald fields to strings

---

tests/integration/event_source_kafka/test_kafka_rules.yml
tests/integration/event_source_kafka/test_kafka_source.py
tests/integration/event_source_url_check/test_url_check_rules.yml
tests/integration/event_source_url_check/test_url_check_source.py
tests/integration/event_source_webhook/test_webhook_rules.yml
tests/integration/event_source_webhook/test_webhook_source.py
tests/integration/utils.py

Tests are failing due to upstream changes in ansible-rulebook.
1. The verbose and debug args merged into -v and -vv respectively.
2. The debug action no longer prepends 'msg' to messages.
Updating the CLIrunner to use new args and fixing the tests.
Closes [AAP-10111](https://issues.redhat.com/browse/AAP-10111).

Fix failing integration tests due to upstream changes

---

extensions/eda/plugins/event_sources/kafka.py
extensions/eda/rulebooks/kafka-test-rules.yml
tests/integration/event_source_kafka/test_kafka_rules.yml
tests/integration/event_source_kafka/test_kafka_source.py
tests/unit/event_source/test_kafka.py

Parse json data if possible, otherwise leave it as pure string. Always place the kafa message under key body in the event placed in the queue.
Resolves AAP-9944: Kafka source plugin only supports json

Kafka plugin accepts non json string

---

extensions/eda/plugins/event_source/webhook.py
tests/integration/event_source_webhook/test_webhook_rules.yml
tests/integration/event_source_webhook/test_webhook_source.py
tests/unit/event_source/test_webhook.py

Client needs to send an bearer authorization token. Enable TLS support if a certificate file is provided.
Resolves AAP-4826: Add security check for webhook and alert manger's local server
We may make TLS default in a future PR.

Add security support to webhook plugin

---

extensions/eda/plugins/event_filter/normalize_keys.py
tests/unit/event_filter/test_normalize_keys.py

The keys in the event payload should follow the convention of of an ansible variable name. A key name can only consist of alpha numeric and under score charachters. All non conforming charachters are converted to _.
https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#creating-valid-variable-names
This is a generic form of the dashes_to_underscore filter, which only translates dashes. This filter translates all non conforming characters

Added an event filter to normalize keys in the event payload

---

extensions/eda/plugins/event_source/webhook.py

Fixes Webhook event source in case the token isn't used/set.
Otherwise it raises `KeyError`.

Fix Webhook source without token

---

.github/workflows/integration-tests.yml
.github/workflows/tests.yml
.github/workflows/tox.ini
.github/workflows/tox.yml
extensions/eda/plugins/event_filter/dashes_to_underscores.py
extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
extensions/eda/plugins/event_filter/json_filter.py
extensions/eda/plugins/event_filter/noop.py
extensions/eda/plugins/event_filter/normalize_keys.py
extensions/eda/plugins/event_source/alertmanager.py
extensions/eda/plugins/event_source/aws_cloudtrail.py
extensions/eda/plugins/event_source/aws_sqs_queue.py
extensions/eda/plugins/event_source/azure_service_bus.py
extensions/eda/plugins/event_source/file.py
extensions/eda/plugins/event_source/file_watch.py
extensions/eda/plugins/event_source/generic.py
extensions/eda/plugins/event_source/journald.py
extensions/eda/plugins/event_source/kafka.py
extensions/eda/plugins/event_source/range.py
extensions/eda/plugins/event_source/tick.py
extensions/eda/plugins/event_source/url_check.py
extensions/eda/plugins/event_source/webhook.py

We needed to update the tox files as a requirement for certification

Add tox.yml and update tox.ini based on eda-partner-testing

---

.github/workflows/integration-tests.yml
.github/workflows/linters.yml
.github/workflows/tests.yml
.github/workflows/tox.yml
README.md

This collection is not pinning any of the requirements versions, if there is an update i.e. in the pytest or ansible lint packages the linters, integration or unit tests might start to fail for unrelated reasons.
This commit add periodic executions in the GH actions workflows and includes a badge per job in the README.md file.

Include periodic jobs execution for the collection

---

extensions/eda/plugins/event_source/aws_sqs_queue.py
extensions/eda/plugins/event_source/url_check.py

This PR fixes failing `tox` action (https://github.com/ansible/event-driven-ansible/actions/runs/5461650644/jobs/9939922571?pr=139#step:4:15) by setting `noqa: perf203`, the `try-except` structure makes sense in these cases.

Failing tox test - use noqa perf203

---

plugins/README.md

Updated unmaintained URL:
From:
https://docs.ansible.com/ansible-core/2.12/plugins/plugins.html
To:
https://docs.ansible.com/ansible/latest/plugins/plugins.html

Update link to latest plugin URL instead of outdated

---

extensions/eda/plugins/event_source/journald.py

Ref https://github.com/ansible/event-driven-ansible/pull/135

journald: basic ruff formating

---

extensions/eda/plugins/event_source/aws_cloudtrail.py

Fixes a minor bug in the aws_cloudtrail event_source plugin where cloudtrail events were retrieved and added to queue twice. The boto3 client `StartTime` parameter needs to be set to the last retrieved event time before the next batch of events is retrieved instead of after.

Fix aws_cloudtrail even duplication bug

---

.gitignore
extensions/eda/plugins/event_source/kafka.py
tests/integration/event_source_kafka/ansible
tests/integration/event_source_kafka/broker_jaas.conf
tests/integration/event_source_kafka/certs-clean.sh
tests/integration/event_source_kafka/certs-create.sh
tests/integration/event_source_kafka/docker-compose.yml
tests/integration/event_source_kafka/test_kafka_rules_plaintext.yml
tests/integration/event_source_kafka/test_kafka_rules_sasl_plaintext.yml
tests/integration/event_source_kafka/test_kafka_rules_sasl_ssl.yml
tests/integration/event_source_kafka/test_kafka_rules_ssl.yml
tests/integration/event_source_kafka/test_kafka_source.py

Add `security_protocol`, `sasl_mechanism`, `sasl_plain_username` and `sasl_plain_password` arguments like aiokafka.AIOKafkaConsumer client.
https://aiokafka.readthedocs.io/en/stable/consumer.html

feat: Add Kafka SASL_SSL authentication

---

.github/workflows/tests.yml

Unit tests fail due to collisions on the same port. Disable parallel execution. 
Example: https://github.com/Alex-Izquierdo/event-driven-ansible/actions/runs/6787231834/job/18449579146

ci: remove parallel execution of unit tests

---

requirements.txt

This was added in a31b892 but was already defined in the requirements.txt file.

Remove duplicate dpath from requirements

---

requirements.txt

This PR:
- adds the `kafka-python` dependency
- sorts the requirements
https://github.com/konstruktoid/event-driven-ansible/actions/runs/7097863427/job/19318725270:
```console
tests/integration/event_source_kafka/test_kafka_source.py:6: in <module>
from kafka import KafkaProducer
E   ModuleNotFoundError: No module named 'kafka'
=========================== short test summary info ============================
ERROR tests/integration/event_source_kafka/test_kafka_source.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.29s ===============================
Error: Process completed with exit code 2.
```

Integration tests: add kafka-python dependency

---

extensions/eda/plugins/event_source/generic.py
tests/unit/event_source/test_generic.py

- The generic plugin can now generated blobs based on the **blob_size** argument. The blob size is specified in bytes and would be in an attribute called *blob*
- Add a **final_payload** option specified as a dict that allows you to send a final payload to be sent after all the events have been sent. This feature can be used to add a custom shutdown event to stop the rulebooks
- Refactorted and added tests

feat: enhance the generic plugin to support blobs

---

requirements.txt

When running tests the systemd-python can't be installed and the tests fail, making the package optional for MacOS

chore: systemd-python not available on MacOS

---

extensions/eda/plugins/event_filter/insert_hosts_to_meta.py

Indentation was incorrect and a colon was missing. I also think that quotes are recommended for values.
And adding the `filters` makes the context a bit clearer.

Fix example in filter insert_hosts_to_meta

---

extensions/eda/plugins/event_source/tick.py
tests/unit/event_source/test_generic.py

black 24.1.0 has introduced at least one new spacing rule and the pipeline errors were driving me crazy so here a fix.

Fix spacing as expected by black

---

extensions/eda/plugins/event_source/pg_listener.py
requirements.txt
tests/unit/event_source/test_pg_listener.py
tests/unit/requirements.txt

This source plugin listens to notifications from the pg_pub_sub 
If the payload is over 7KB the sender chunks messages which pg_listener assembles before calling the rule engine.
https://issues.redhat.com/browse/AAP-19049

feat: added pg_listener source plugin

---

extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
extensions/eda/plugins/event_source/webhook.py
tests/unit/event_filter/test_insert_hosts_to_meta.py
tox.ini

https://issues.redhat.com/browse/AAP-17232

feat: add raise_error and log_error option to insert_hosts_to_meta filter

---

extensions/eda/rulebooks/git-hook-deploy-rules.yml
extensions/eda/rulebooks/git-hook-test-rules.yml
extensions/eda/rulebooks/github-ci-cd-rules.yml

In a rulebook when we define a condition we cannot use Jinja substitution, instead the vars namespace should be used to get values from the passed in extra vars.
https://issues.redhat.com/browse/AAP-20843

chore: fixed examples to use vars instead of jinja

---

.ansible-lint
.ansible-lint.yml
CHANGELOG.md
extensions/eda/rulebooks/github-ci-cd-rules.yml
galaxy.yml
playbooks/hello.yml
plugins/modules/upcase.py

Some minor changes required for the certification. 
- Adds a changelog
- Exclude some sample content for ansible-lint
- Some minor fixes for lint warnings. 
- Bump to 1.4.7

chore: add changelog, fix lint issues and bump 1.4.7

---

extensions/eda/plugins/event_source/kafka.py
tests/integration/event_source_kafka/test_kafka_rules_headers.yml
tests/integration/event_source_kafka/test_kafka_source.py
tests/unit/event_source/test_kafka.py

Support headers

---

extensions/eda/rulebooks/demo_rulebook.yml

We need a simple rulebook for Quick Startup guide that does not connect to the controller. The other rulebook we have requires a controller.

docs: added a simple rulebook for demo purposes

---

extensions/eda/plugins/event_source/generic.py
tests/unit/event_source/test_generic.py

This feature allows you to store an array of events in a yaml file and load the events from the yaml file when the rulebook is running. The new argument is called **payload_file**

feat: generic source supports events in yaml file

---

.github/release-drafter.yml
.github/workflows/ack.yml
.github/workflows/push.yml

This change will make use of release drafter for drafting changelog updates on https://github.com/ansible/event-driven-ansible/releases so it would be much easier to know what was merged and if a release is needed or not.

chore: enable release-drafter

---

.github/workflows/tox.yml
requirements.txt
tests/unit/requirements.txt
tox.ini

This fixes a bug that prevented the execution of the tests on some platforms, such macos, as psycopg listed alone does not always installs a functional library:
```
E   ImportError: no pq wrapper available.
E   Attempts made:
E   - couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
E   - couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
E   - couldn't import psycopg 'python' implementation: libpq library not found
```
Also enables testing on macos using aarch64, preventing a regression related to unavailable dependencies.
Related: #219

Correct psycopg requirements

---

.github/workflows/tox.yml

This should give us access to newer dependencies and avoid surprises
cause by use of ubuntu-latest mobile label.
Related: #219

Ensure we use ubuntu 24.04 runners for testing

---

README.md
demos/dynatrace-demo/instructions.md
meta/runtime.yml
requirements.txt
test_requirements.txt

- Mention ansible-core>=2.15 in meta/runtime.yml
- Mention ansible-core>=2.15 in runtime requirements to avoid accidents during testing
- Avoid mentioning 'ansible' community bundle in test_requirements.txt
- Correct docs badges
- Remove ansible-rulebook requirement from readme, being a test dependency
- Mention code block types in readme
- Added minimal versions for test requirements (performance and supportability)

Correct requirements and update docs

---

.config/dictionary.txt
.github/workflows/tox.yml
bindep.txt
tox.ini

- Adds bindep file
- Enable testing of bindep fi on CI/CD via tox-extra plugin

Add bindep file for testing system dependencies

---

.github/workflows/tox.yml
bindep.txt
tox.ini

Note that we run sanity with py39, which will make use of ansible 2.15, and with py39 which will make use of ansible 2.17, which do have a different range of python versions they do test with.

Run sanity with all supported python versions

---

.github/workflows/tox.yml
requirements.txt

To be noted that without this change, integration tests would fail with python3.12. We could switch to `kafka-python-ng` for all versions, but I considered that to reduce impact as I do not know what other changes were merged in to that branch.

Add support for python 3.12

---

CONTRIBUTING.md
test_requirements.txt
tests/integration/event_source_kafka/test_kafka_source.py

As python based docker-compose is unmaintained and with last release more than 3 year old, we make use of podman-compose instead, which is a wrapper that can make use of any docker-compose if found, in addition to native podman-compose tool.

Replace unmaintained docker-compose with podman-compose

---

.pre-commit-config.yaml
extensions/eda/plugins/event_source/aws_sqs_queue.py
extensions/eda/plugins/event_source/webhook.py
pyproject.toml

Related: #258
Upstream links:
- https://github.com/aio-libs/aiobotocore/issues/1133
- https://github.com/aio-libs/aiokafka/issues/980
- https://github.com/ansible/ansible/issues/83801
- https://github.com/timsavage/asyncmock/issues/8
- https://github.com/boto/botocore/issues/2297
- https://github.com/dpkp/kafka-python/issues/2446

Enable mypy with minimal checks

---

extensions/eda/plugins/event_source/aws_cloudtrail.py
extensions/eda/plugins/event_source/aws_sqs_queue.py
extensions/eda/plugins/event_source/generic.py
extensions/eda/plugins/event_source/kafka.py
extensions/eda/plugins/event_source/pg_listener.py
pyproject.toml
tests/integration/event_source_url_check/test_url_check_source.py

Address more typing errors

---

.config/dictionary.txt
plugins/modules/project.py
plugins/modules/project_info.py
tests/integration/targets/project/tasks/create.yml
tests/integration/targets/project/tasks/delete.yml
tests/integration/targets/project/tasks/main.yml
tests/integration/targets/project/tasks/update.yml
tests/integration/targets/project_info/tasks/create.yml
tests/integration/targets/project_info/tasks/main.yml

* Create, Update, and delete project from EDA controller

Add project module

---

.config/dictionary.txt
plugins/module_utils/controller.py
pyproject.toml
tests/unit/plugins/module_utils/test_client.py
tests/unit/plugins/module_utils/test_controller.py

Add some unit tests for module_utils

Refactor plugins/module_utils/controller.py for better testing

---

CONTRIBUTING.md
README.md

This PR updates the README doc to match the [template](https://access.redhat.com/articles/7068606)

Update README to match the template

---

.config/dictionary.txt
meta/runtime.yml
plugins/modules/activation.py
plugins/modules/activation_info.py
tests/integration/targets/activation/tasks/main.yml

Add activation and activation_info modules

Add activation and activation_info modules

---

.github/workflows/tox.yml
tox.ini

Speedup GHA execution by running sanity within lint job and avoiding
to run each before each unit test one.
It should be noted that sanity tox execution is already running for
all python versions anyway, so there is no need to run it more than
once.
Related: #272

Run sanity check after linting

---

plugins/module_utils/arguments.py
plugins/module_utils/common.py
plugins/module_utils/controller.py
plugins/modules/activation.py
plugins/modules/activation_info.py
plugins/modules/controller_token.py
plugins/modules/credential.py
plugins/modules/credential_info.py
plugins/modules/credential_type.py
plugins/modules/credential_type_info.py
plugins/modules/decision_environment.py
plugins/modules/decision_environment_info.py
plugins/modules/project.py
plugins/modules/project_info.py
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt
tests/sanity/ignore-2.18.txt

This change adds minimal types and uncovers several logic bugs, where users of controller.get_one_or_many assumed it will not return a list.
I had to replace some calls of `get_one_or_many` with `get_exactly_one`, so please double check them.
Depends-On: #271

Add some critical types to module_utils and fix logic

---

bindep.txt
tox.ini

- restore tox-extra plugin
- update bindep.txt to remove rsync (RTD) but add a check for it in tox.ini docs
- bindep: avoid installing extra python version all the time (soft test deps)
- assure we force install collection before building docs

Make docs building logic more resilient

---

plugins/module_utils/common.py
plugins/module_utils/controller.py
plugins/modules/activation.py
plugins/modules/activation_info.py
plugins/modules/controller_token.py
plugins/modules/credential.py
plugins/modules/credential_info.py
plugins/modules/credential_type.py
plugins/modules/credential_type_info.py
plugins/modules/decision_environment.py
plugins/modules/decision_environment_info.py
plugins/modules/project.py
plugins/modules/project_info.py
plugins/modules/user.py
tests/unit/plugins/module_utils/test_common.py

Cleanup module_utils and ensure consistence in the code base
Will rebase after https://github.com/ansible/event-driven-ansible/pull/274 is merged

Cleanup module_utils and ensure consistence in the code base

---

.gitignore
.pre-commit-config.yaml
changelogs/config.yaml
cspell.config.yaml
tox.ini

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
- Docs Pull Request

Enable changelogs for collection

---

plugins/doc_fragments/eda_controller.py

Fix a wrong reference for the CONTROLLER_HOST environment variable in the module docs.

docs: fix CONTROLLER_HOST environment variable

---

plugins/modules/activation.py

Fix the default values for the log_level and restart_policy parameters in the activation module to match the default values of the API and UI
Jira: https://issues.redhat.com/browse/AAP-31234

fix: update log_level and restart_policy default values

---

plugins/modules/event_stream.py
tests/integration/targets/activation/tasks/main.yml
tests/integration/targets/event_stream/tasks/main.yml

event stream type is mandatory. Tests fail with:
```
TASK [activation : Create an event stream] *************************************
fatal: [testhost]: FAILED! => {"changed": false, "msg": "state is present but all of the following are missing: event_stream_type"}
```

fix: ensure correct required params for event streams

---

plugins/modules/event_stream.py
tests/integration/targets/event_stream/tasks/main.yml

event_stream - add support for `headers` and `forward_events` options

event_stream - add support for headers and forward_events options

---

.github/workflows/tox.yml
galaxy.yml
plugins/module_utils/client.py
plugins/module_utils/controller.py
plugins/modules/project.py
tests/integration/targets/project/tasks/create.yml
tests/integration/targets/project/tasks/delete.yml
tests/integration/targets/project/tasks/main.yml
tests/integration/targets/project/tasks/sync.yml

**Why:**
Project module misses the sync capability. An existing project can be synced (pull changes from the repo) and this have be able to be done from the module. 
jira: https://issues.redhat.com/browse/AAP-32264
**How:**
We remove the constraint to define the url when state is present because the project might already exists, url is only required when the project needs to be created, we check it in advance to check the requirement of the url and to check if the sync operation can be performed. We add the new parameter "sync" to run the synchronization (it is an async task in the backend) if the project already exists. The client needs to be updated because the backend can also return 202 for a POST operation. 
Include:
- A new sync parameter and logic related. 
- A new generic "create" …

feat: add sync capability to project module

---

tests/integration/targets/activation/tasks/main.yml
tests/integration/targets/event_stream/tasks/main.yml

Fix integration tests by ensuring the appropriate event_stream_type is used

Fix integration tests

---

plugins/modules/event_stream.py
tests/integration/targets/event_stream/tasks/main.yml

event_stream - Ensure forward_events works as expected

event_stream - Ensure forward_events works as expected

---

plugins/module_utils/controller.py
tests/integration/targets/credential/tasks/main.yml
tests/integration/targets/event_stream/tasks/main.yml

Ensure modules are idempotent

---

plugins/modules/event_stream.py
tests/integration/targets/activation/tasks/main.yml
tests/integration/targets/event_stream/tasks/main.yml

event_stream_type is not necessary to create the event stream and it is misleading since the user has no way to know what is the value for it and it will end up in unexpected errors if its sent to the api. The type is already set by the backend based on the credential chosen. The API will remove it as well, its existence is an error and it only exists in the UI in order to filter existing credentials by type. 
Jira: https://issues.redhat.com/browse/AAP-33196

fix: remove event_stream_type for event_stream module

---

plugins/modules/rulebook_activation.py
plugins/modules/rulebook_info.py

Ensure that the mandatory fields required by the EDA API are respected within the modules.

Ensure that the mandatory fields required by the EDA API are respected within the modules.

---

extensions/eda/plugins/event_source/file_watch.py

Avoid QueueFull exception by using queue.put instead of queue.put_nowait, no need to catch the exception, await queue.put() implements backpressure natively.
Closes https://github.com/ansible/event-driven-ansible/issues/130

fix: Avoid QueueFull exception in file_watch source plugin

---

extensions/eda/plugins/event_source/generic.py
tests/unit/event_source/test_generic.py

From EDA credentials we might pass in env vars for source plugins, the generic source plugin can optionally have a dictionary of env vars that it can check
e.g.
```
check_env_vars:
ENV_V1: value1
ENV_V2: value2
```
https://issues.redhat.com/browse/AAP-35597

feat: optionally check if all env vars match

---

plugins/module_utils/common.py
plugins/modules/rulebook_activation.py
tests/integration/targets/activation/tasks/main.yml

Decision Environment, organization, project and rulebook are mandatory for the activation. If the lookup of these resources fail or don't exist, the module sends a request that fails and returns a confusing error to the user like:
```
TASK [Activate a rulebook] *****************************************************
2024-11-07T12:43:17Z ifxry5zyniyz INFO: setup-control: fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to create/update rulebook activation: HTTP error
{'rulebook_id': ['This field is required.']}
"}
```
Ensure these params and handle properly their absence. 
Jira: https://issues.redhat.com/browse/AAP-35360

fix: ensure mandatory params for activation

---

.github/workflows/tox.yml

We want to publish only with a new tag. This prevent errors like https://github.com/ansible/event-driven-ansible/actions/runs/11897747368 
Follow up https://github.com/ansible/event-driven-ansible/pull/330/

ci: make publication only run with tags

---

tox.ini

Solves CI failing pipelines by pinning tox-extra dependency. 
Ref: https://github.com/tox-dev/tox-extra/issues/121

ci: pin tox-extra version

---

plugins/modules/rulebook_activation.py
tests/integration/targets/activation/tasks/main.yml

Addresses #365 by checking if module parameters which represent flags are defined, preventing evaluation of their truthyness. Current behavior will ignore an incoming value of false and default back to true because of the conditional logic:
Example:
`module.params["enabled"] = False`
`if module.params.get("enabled")` evaluates to False, but the intent is to determine if it has been defined, so we want this to evaluate to True.
This PR addresses the same issue for `swap_single_source` param.

Check if param flag values are defined, not truthiness

---

tests/integration/targets/decision_environment/tasks/main.yml
tests/integration/targets/decision_environment_info/tasks/main.yml

https://issues.redhat.com/browse/AAP-38952
The 'image_url' field is incorrect in the decision_enrivonment tests and it does not correspond to valid OCI image/tag/naming standards.
Proper validation of the image_url field was introduced here [1], and the tests of the collection must reflect it.
[1] https://github.com/ansible/eda-server/pull/1188

fix: [AAP-38952] incorrect 'image_url' in tests

---

extensions/eda/plugins/event_source/pg_listener.py
tests/unit/event_source/test_pg_listener.py

What:
This PR adds support for a dictionary of pg_param:value for the connection follow the standard use of [Connection.connect](https://www.psycopg.org/psycopg3/docs/api/connections.html) with backward compatibility. Also enhances the validation of plugin arguments, extends test coverage and update module docstring according to the changes. 
* New dict param `postgres_params`
* Check that dsn or postgres_params are defined
* Check required params (channels)
* Check the right type of all the arguments
Why:
Psycopg library has native support for a dsn string and kwargs params. There is no need to force the definition of a connection string, key:value pairs are more usual and makes easier the integration since it can be handled as a structured data. 
This is also related to …

feat: support kwargs for pg conn in pg_listener

---

.config/dictionary.txt
extensions/eda/plugins/event_filter/dashes_to_underscores.py
extensions/eda/plugins/event_filter/insert_hosts_to_meta.py
extensions/eda/plugins/event_filter/json_filter.py
extensions/eda/plugins/event_filter/noop.py
extensions/eda/plugins/event_filter/normalize_keys.py
extensions/eda/plugins/event_source/alertmanager.py
extensions/eda/plugins/event_source/aws_cloudtrail.py
extensions/eda/plugins/event_source/aws_sqs_queue.py

This PR adds documentation for both event sources alertmanager, aws_cloudtrail and aws_sqs_queue, by following the format outlined [here](https://docs.ansible.com/ansible-core/devel/dev_guide/sidecar.html).
JIRA: [AAP-38755](https://issues.redhat.com/browse/AAP-38755)

feat: [AAP-38755] add documentation for alertmanager, aws_cloudtrail and aws_sqs_queue plugins

---

extensions/eda/plugins/event_source/azure_service_bus.py
extensions/eda/plugins/event_source/file.py
extensions/eda/plugins/event_source/file_watch.py

This PR adds documentation for both event sources azure_service_bus, file and file_watch plugins, by following the format outlined [here](https://docs.ansible.com/ansible-core/devel/dev_guide/sidecar.html).
JIRA: [AAP-38755](https://issues.redhat.com/browse/AAP-38755)

feat: [AAP-38755] add documentation for azure_service_bus, file and file_watch plugins

---

extensions/eda/plugins/event_source/generic.py
extensions/eda/plugins/event_source/journald.py
extensions/eda/plugins/event_source/kafka.py

This PR adds documentation for both event sources generic, journald and kafka plugins, by following the format outlined [here](https://docs.ansible.com/ansible-core/devel/dev_guide/sidecar.html).
JIRA: [AAP-38755](https://issues.redhat.com/browse/AAP-38755)

feat: [AAP-38755] add documentation for generic, journald and kafka plugins

---

extensions/eda/plugins/event_source/aws_cloudtrail.py
extensions/eda/plugins/event_source/aws_sqs_queue.py
extensions/eda/plugins/event_source/pg_listener.py

A few of the `event_source` plugins had invalid DOCUMENTATION due to YAML syntax errors, this PR addresses them by using folded or block scalars.
Generally, if there is a `:` in the string, with whitespace to the right, YAML will split it as a key/value pair. Using folded or block scalars will resolve the issue as the whole field will be treated as a string.

Fix YAML syntax issues in DOCUMENTATION

---

plugins/modules/credential.py
tests/integration/targets/credential/tasks/main.yml

This PR adds support for EDA Credentials' new copy endpoint - `/eda-credentials/<id>/copy`.

feat: [AAP-37428] add support for copy credential

---

galaxy.yml
plugins/modules/credential.py
plugins/modules/rulebook_activation.py

Also includes a minor fix in the documentation from the latest changes about copy activation/credential, which is not a breaking change.

chore: release 2.6

---

.config/dictionary.txt
.github/workflows/tox.yml
extensions/eda/plugins/event_source/kafka.py
requirements.txt
tests/unit/requirements.txt
tox.ini

The aiokafka package already supports GSSAPI as long as it has the correct packages installed along with kerberos.
This fix just passes in the parameters from EDA to aiokafka
The DE should have the following Kerberos packages on CentOS:
* krb5-libs
* krb5-devel
Along with the python gssapi package.
https://issues.redhat.com/browse/AAPRFE-1662

fix: add support for Kafka GSSAPI

---

.gitignore
plugins/module_utils/client.py
plugins/module_utils/controller.py
plugins/modules/rulebook_activation.py
tests/integration/targets/activation/tasks/activation_lifecycle.yml
tests/integration/targets/activation/tasks/main.yml

Rulebook activation [module](https://console.redhat.com/ansible/automation-hub/repo/published/ansible/eda/content/module/rulebook_activation/) lacks support for restarting the activation. As any existing operation it should be supported. 
Jira: https://issues.redhat.com/browse/AAP-37681

fix: add restart activation AAP-37681

---

plugins/modules/project.py
tests/integration/targets/project/tasks/create.yml
tests/integration/targets/project/tasks/main.yml
tests/run-staging

This PR adds a missing param for adding `proxy` when creating a project through project module.
JIRA: [AAP-41820](https://issues.redhat.com/browse/AAP-41820)

fix: [AAP-41820] add proxy param for project create module

---

plugins/modules/rulebook_activation.py
tests/integration/targets/activation/tasks/main.yml

https://issues.redhat.com/browse/AAP-40577
This also covers enabling and disabling rulebook activations, as well
as updating other fields like name, log_level, credentials, and so on.

feat [AAP-40577]: add support for edit activations

---

.config/dictionary.txt
.config/manifest.txt
meta/runtime.yml
plugins/module_utils/controller.py
plugins/modules/rulebook_activation.py
plugins/modules/rulebook_activation_copy.py
tests/integration/targets/activation/tasks/main.yml
tests/run-staging

A new module is created for the copy action to copy the activation.
It has been discussed and decided that we shall move the existing copy action from the activation module to a separate module. The copy action shall take only one parameter which is the name of the copied activation. The resulting activation should be in disabled state. [https://issues.redhat.com/browse/AAP-42215]

Move Activation Copy to Separate Module-AAP-42215

---

galaxy.yml

- bump to a new release with no changes from v2.6.0 to trigger plugin documentation generation on Automation Hub.

chore: release 2.6.1

---

extensions/eda/plugins/event_source/alertmanager.py
extensions/eda/plugins/event_source/webhook.py

- add folded scalar to treat `:` as a text in documentation content.
JIRA: [AAP-42971](https://issues.redhat.com/browse/AAP-42971)

fix: [AAP-42971] fix syntax issues in event source plugins

---

extensions/eda/plugins/event_source/aws_sqs_queue.py
tests/unit/event_source/test_aws_sqs_queue.py

Based on feedback we received we are missing some key parameters from sqs queue processing. Adding additional optional parameters
* queue_owner_aws_account_id
* max_number_of_messages
https://issues.redhat.com/browse/AAP-42623
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/get_queue_url.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sqs/client/receive_message.html

fix: pass in optional arguments to sqs

---

galaxy.yml

Bump to a new release from v2.6.1 to 2.7.0

chore: release 2.7.0

---

.github/dependabot.yml

The right key to exclude dependencies in an ecosystem is "ignore", not "exclude", as documented:
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
Fixes commit 5659368a586fba30802e67d835c02420f45333f9.

chore: fix the dependabot configuration

---

extensions/eda/plugins/event_source/url_check.py
tests/integration/event_source_url_check/test_url_check_rules_urls.yml
tests/integration/event_source_url_check/test_url_check_source.py

The existing logic would had caused the check to stop whenever an URL cannot be reached, no matter the reason.
Change the logic to handle the exception (in case of a request failure) within the loop for the URLs; this way, even if one fails, the remaining can still be checked. Note that the reported status is still "down" in any case: potential improvements to the reporting of check failures are to be addressed separately.
Add an additional test case for it, modelled after the existing test, to check that even in case of mixed situations (e.g. reacheable, etc) all the expected results are provided.
Fixes: https://github.com/ansible/event-driven-ansible/issues/165
Fixes: https://issues.redhat.com/browse/AAP-15246

fix: really check all the URLs in url_check

---

pyproject.toml

pylint 3 introduces `too-many-positional-arguments` to help distinguish from `many positional-or-keyword` and `positional-only`; since we already disable the former, disable also the new checker.

chore: disable pylint too-many-positional-arguments

---

tests/integration/targets/project/tasks/update.yml

As per this PR [1], the project scm_url is now editable.
This commit simply fixes the integration test by checking that a project is updated when the URL is changed.
This integration test was previously failing because the old logic was passing a different URL in the parameters, but considering that the result was not changed. But now the project URL is editable and the test should consider the task as changed.
[1] https://github.com/ansible/eda-server/pull/1315

fix: [AAP-41454] adjust project url edit test

---

tests/integration/targets/project/tasks/scm_branch.yml

https://issues.redhat.com/browse/AAP-41467
As per this PR on eda-server [1], the project URL is now editable. In a previous PR in the collection [2] we already make sure that an update in the project URL causes a change status in the project, and the task returns as such.
This commit simply removes an unecessary "sync: true" that is being passed along with the request to update the project URL, given the sync is already triggered due to this change [3].
[1] https://github.com/ansible/eda-server/pull/1315
[2] https://github.com/ansible/event-driven-ansible/pull/439
[3] https://github.com/ansible/eda-server/pull/1323

fix: [AAP-41467] don't fail on project sync already in progress

---

plugins/modules/rulebook_activation.py
tests/integration/targets/activation/tasks/main.yml

https://issues.redhat.com/browse/AAP-50916
This fixes a bug where rulebook activations with event streams were considered different even though the parameters of the tasks were the same. The cause was a difference between the information returned from the backend and the return from `yaml.dump()` when parsing the event streams from the task parameter. The `yaml.dump()` adds a trailing newline at the end of the dumped YAML string, which is the default behavior. E.g:
info from the eda-server:
```
'source_mappings': '- event_stream_id: 12\\n  event_stream_name: Test_EventStream_c99484c1-45a1-5c5f-a067-877f4e002f9c\\n  rulebook_hash: 1e0f22025ab0a4e729fb68bcb9497412c3d9f477ce5a8cb91cc2ef15e35c4dc6\\n  source_name: __SOURCE_1'
```
return from parsing the task's event streams parameter with …

fix: [AAP-50916] fix rulebook activation idempotence
